# Generated by Django 4.0.4 on 2022-12-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(default='user.png', upload_to='images/')),
                ('votes', models.IntegerField(default=0)),
                ('isDiva', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(default='user.png', upload_to='images/')),
                ('votes', models.IntegerField(default=0)),
                ('isDiva', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('otp', models.CharField(max_length=4)),
                ('diva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.diva')),
                ('hunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hunk')),
            ],
        ),
    ]
