# Generated by Django 4.0.4 on 2022-12-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_diva_isdiva_remove_hunk_isdiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='diva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.diva'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='hunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hunk'),
        ),
    ]
