# Generated by Django 4.0.4 on 2022-12-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_voter_diva_alter_voter_hunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='diva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.diva'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='hunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hunk'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
