# Generated by Django 4.1.4 on 2022-12-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_voter_diva_alter_voter_hunk_alter_voter_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
