# Generated by Django 4.1.5 on 2023-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_voter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diva',
            name='college',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hunk',
            name='college',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
